import uuid
from typing import Protocol

from app.domain.entities import Account, Organization, User


class AccountRepository(Protocol):
    async def create(self, account: Account) -> Account: ...
    async def get_by_id(self, account_id: uuid.UUID) -> Account | None: ...


class OrganizationRepository(Protocol):
    async def create(self, organization: Organization) -> Organization: ...
    async def count_active_for_account(self, account_id: uuid.UUID) -> int: ...


class UserRepository(Protocol):
    async def create(self, user: User) -> User: ...
    async def get_by_email(self, email: str) -> User | None: ...


class PasswordHasher(Protocol):
    def hash(self, plain: str) -> str: ...


class UnitOfWork(Protocol):
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
