import uuid
from dataclasses import dataclass
from typing import Protocol

from app.domain.entities import (
    Account,
    AgentToken,
    Firewall,
    Organization,
    RefreshToken,
    Snapshot,
    User,
)


class AccountRepository(Protocol):
    async def create(self, account: Account) -> Account: ...
    async def get_by_id(self, account_id: uuid.UUID) -> Account | None: ...


class OrganizationRepository(Protocol):
    async def create(self, organization: Organization) -> Organization: ...
    async def count_active_for_account(self, account_id: uuid.UUID) -> int: ...
    async def list_active_for_account(self, account_id: uuid.UUID) -> list[Organization]: ...


class UserRepository(Protocol):
    async def create(self, user: User) -> User: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_id(self, user_id: uuid.UUID) -> User | None: ...


class RefreshTokenRepository(Protocol):
    async def create(self, token: RefreshToken) -> RefreshToken: ...
    async def get_by_token_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def revoke(self, token_id: uuid.UUID) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, plain: str) -> str: ...


class PasswordVerifier(Protocol):
    def verify(self, plain: str, hashed: str) -> bool: ...


@dataclass(frozen=True)
class AccessTokenClaims:
    user_id: uuid.UUID
    account_id: uuid.UUID


class TokenService(Protocol):
    def create_access_token(self, user_id: uuid.UUID, account_id: uuid.UUID) -> str: ...
    def decode_access_token(self, token: str) -> AccessTokenClaims: ...
    def generate_refresh_token(self) -> str: ...
    def hash_refresh_token(self, plain: str) -> str: ...


class FirewallRepository(Protocol):
    async def create(self, firewall: Firewall) -> Firewall: ...
    async def get_by_id(self, firewall_id: uuid.UUID) -> Firewall | None: ...
    async def list_active_for_org(
        self, organization_id: uuid.UUID, cursor: uuid.UUID | None, limit: int
    ) -> list[Firewall]: ...
    async def update(self, firewall: Firewall) -> Firewall: ...
    async def record_check_in(
        self, firewall_id: uuid.UUID, pfsense_version: str | None
    ) -> None: ...


class AgentTokenRepository(Protocol):
    async def create(self, token: AgentToken) -> AgentToken: ...
    async def get_active_for_firewall(self, firewall_id: uuid.UUID) -> AgentToken | None: ...
    async def revoke_all_for_firewall(self, firewall_id: uuid.UUID) -> None: ...
    async def get_by_token_hash(self, token_hash: str) -> AgentToken | None: ...


class SnapshotRepository(Protocol):
    async def create(self, snapshot: Snapshot) -> Snapshot: ...
    async def list_queued(self, limit: int = 10) -> list[Snapshot]: ...
    async def update_status(self, snapshot_id: uuid.UUID, status: str) -> None: ...


class UnitOfWork(Protocol):
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
